### ISSUE TITLE
Fail to extract h264 from some pcap file

### ISSUE THREAD

**Issue by annyyuan** [volvet/h264extractor#1]
I get packets using wireshark, but can't extract h264 from it. Please fix it.

**Comment by volvet** [comment]
as the pcap file you provided,   I can extract h264 stream correctly,   it is SVC stream, so can't be analyzed by elecard stream eye or AVC decoder.  you can try JSVM codec or openh264 to analyze.  
   openh264:   https://github.com/cisco/openh264
