### ISSUE TITLE
Not filtering any packet

### ISSUE THREAD

**Issue by EricTsai-TW** [volvet/h264extractor#2]
I need to change
local h264_tap = Listener.new("ip")
to
local h264_tap = Listener.new(tap, "h264")
to get it work.
(Must decode UDP as RTP and set H264 payload type first)
I don't know why...

**Comment by volvet** [comment]
I guess "local h264_tap = listener.new("ip", "h264")"  is better.  
https://github.com/volvet/h264extractor/commit/b5e2ff3568a72b75b3b06f921976072ec777f705

see https://wiki.wireshark.org/LuaAPI/Listener
